OUTPUT_DIR: "Log/retrieval_vis_emb_e2e"
MODEL:
  E2E: True
  META_ARCHITECTURE: "OneStage"
  ONE_STAGE_HEAD: "align" 
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-50"
  NECK:
    CONV_BODY: "fpn-align"
  FCOS:
    NUM_CLASSES: 2 
  ALIGN:

    NUM_CONVS: 2
    POOLER_RESOLUTION: (4, 15)
    POOLER_SCALES: (0.25, 0.125, 0.0625) 
DATASETS:
  TRAIN: ("synthtext90k",)
  TEST: ("svt_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 8
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (12000,23000) 
  MAX_ITER: 35000 
  IMS_PER_BATCH: 168 
  CHECKPOINT_PERIOD: 1000
  RESUME: True
TEST:
  IMS_PER_BATCH: 1
  BBOX_AUG:
    ENABLED: False
INPUT:
  AUGMENT: "PSSAugmentation"
  PIXEL_MEAN: [103.53, 116.28, 123.675]
  PIXEL_STD: [57.375, 57.12, 58.395]
  BRIGHTNESS: 0.125
  CONTRAST: 0.125
  SATURATION: 0.5
  HUE: 0.5
  USE_RANDOM_E: True
  USE_RANDOM_R: False
  USE_RANDOM_HF: False
  USE_RANDOM_VF: True
